In [ ]:
import pandas as pd

In [ ]:
games_data=pd.read_csv("games.csv")
games_data

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
0,0,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",17K,3.8K,4.6K,4.8K
1,1,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,21K,3.2K,6.3K,3.6K
2,2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","['Nintendo', 'Nintendo EPD Production Group No...",4.4,4.3K,4.3K,"['Adventure', 'RPG']",The Legend of Zelda: Breath of the Wild is the...,['This game is the game (that is not CS:GO) th...,30K,2.5K,5K,2.6K
3,3,Undertale,"Sep 15, 2015","['tobyfox', '8-4']",4.2,3.5K,3.5K,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...","A small child falls into the Underground, wher...",['soundtrack is tied for #1 with nier automata...,28K,679,4.9K,1.8K
4,4,Hollow Knight,"Feb 24, 2017",['Team Cherry'],4.4,3K,3K,"['Adventure', 'Indie', 'Platform']",A 2D metroidvania with an emphasis on close co...,"[""this games worldbuilding is incredible, with...",21K,2.4K,8.3K,2.3K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1507,1507,Back to the Future: The Game,"Dec 22, 2010",['Telltale Games'],3.2,94,94,"['Adventure', 'Point-and-Click']",Back to the Future: The Game is one of Telltal...,['Very enjoyable game. The story adds onto the...,763,5,223,67
1508,1508,Team Sonic Racing,"May 21, 2019","['Sumo Digital', 'Sega']",2.9,264,264,"['Arcade', 'Racing']",Team Sonic Racing combines the best elements o...,"['jogo morto mas bom', 'not my cup of tea', ""C...",1.5K,49,413,107
1509,1509,Dragon's Dogma,"May 22, 2012",['Capcom'],3.7,210,210,"['Brawler', 'RPG']","Set in a huge open world, Dragon’s Dogma: Dark...","['Underrated.', 'A grandes rasgos, es como un ...",1.1K,45,487,206
1510,1510,Baldur's Gate 3,"Oct 06, 2020",['Larian Studios'],4.1,165,165,"['Adventure', 'RPG', 'Strategy', 'Tactical', '...","An ancient evil has returned to Baldur's Gate,...",['Bu türe bu oyunla girmeye çalışmak hataydı s...,269,79,388,602
1511,1511,The LEGO Movie Videogame,"Feb 04, 2014","['WB Games', 'TT Fusion']",2.8,184,184,"['Adventure', 'Puzzle']",Join Emmet and an unlikely group of resistance...,"['Legal', 'Pretty Average Lego Game But It Was...",1.7K,11,239,73

In [ ]:
games_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1512 entries, 0 to 1511
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         1512 non-null   int64
 1   Title              1512 non-null   object
 2   Release Date       1512 non-null   object
 3   Team               1511 non-null   object
 4   Rating             1499 non-null   float64
 5   Times Listed       1512 non-null   object
 6   Number of Reviews  1512 non-null   object
 7   Genres             1512 non-null   object
 8   Summary            1511 non-null   object
 9   Reviews            1512 non-null   object
 10  Plays              1512 non-null   object
 11  Playing            1512 non-null   object
 12  Backlogs           1512 non-null   object
 13  Wishlist           1512 non-null   object
dtypes: float64(1), int64(1), object(12)
memory usage: 165.5+ KB

#Data Cleaning

In [ ]:
from IPython.core.interactiveshell import dis
import pandas as pd
from collections import Counter
# 1. Convert the "stringified" lists into actual Python lists
import ast
#games_data['Genres'] = games_data['Genres'].apply(ast.literal_eval)
# 2. Now explode them into individual items and convert to a list
#all_genres_list = games_data['Genres'].explode().tolist()
# View the result
#genres_list=(list(set(all_genres_list)))
#counts = Counter(games_data['Genres'].explode().tolist())
#counts
#Adventure 1014
#RPG 523
#Platform 329
#Shooter 353
#Indie 284
games_data['Adventure']=0
games_data['RPG']=0
games_data['Platform']=0
games_data['Shooter']=0
games_data['Indie']=0
for i in range(len(games_data['Genres'] )):
  if 'Adventure' in (games_data.loc[i,'Genres']):
    games_data.loc[i,'Adventure']=1
  if 'RPG' in (games_data.loc[i,'Genres'] ):
    games_data.loc[i,'RPG']=1
  if 'Platform' in (games_data.loc[i,'Genres'] ):
    games_data.loc[i,'Platform']=1
  if 'Shooter' in (games_data.loc[i,'Genres'] ):
    games_data.loc[i,'Shooter']=1
  if 'Indie' in (games_data.loc[i,'Genres'] ):
    games_data.loc[i,'Indie']=1
games_data[['Adventure','RPG','Platform','Shooter','Indie']]

      Adventure  RPG  Platform  Shooter  Indie
0             1    1         0        0      0
1             1    1         0        0      1
2             1    1         0        0      0
3             1    1         0        0      1
4             1    0         1        0      1
...         ...  ...       ...      ...    ...
1507          1    0         0        0      0
1508          0    0         0        0      0
1509          0    1         0        0      0
1510          1    1         0        0      0
1511          1    0         0        0      0

[1512 rows x 5 columns]

### remove duplicate and handle null values in ratings,plays and sales.

In [ ]:
for i in range(len(games_data['Plays'])):
  if 'K' in games_data.loc[i]['Plays']:
    games_data.loc[i,'Plays']=float(games_data.loc[i,'Plays'][0:-1])*1000

In [ ]:
for i in range(len(games_data['Times Listed'])):
  if 'K' in (games_data.loc[i,'Times Listed']):
    games_data.loc[i,'Times Listed']=(float(games_data.loc[i,'Times Listed'][0:-1])*1000)

In [ ]:
for i in range(len(games_data['Number of Reviews'])):
  if 'K' in (games_data.loc[i,'Number of Reviews']):
    games_data.loc[i,'Number of Reviews']=(float(games_data.loc[i,'Number of Reviews'][0:-1])*1000)

In [ ]:
for i in range(len(games_data['Playing'])):
  if 'K' in (games_data.loc[i,'Playing']):
    games_data.loc[i,'Playing']=(float(games_data.loc[i,'Playing'][0:-1])*1000)

In [ ]:
for i in range(len(games_data['Backlogs'])):
  if 'K' in (games_data.loc[i,'Backlogs']):
    games_data.loc[i,'Backlogs']=(float(games_data.loc[i,'Backlogs'][0:-1])*1000)

In [ ]:
for i in range(len(games_data['Wishlist'])):
  if 'K' in (games_data.loc[i,'Wishlist']):
    games_data.loc[i,'Wishlist']=(float(games_data.loc[i,'Wishlist'][0:-1])*1000)

In [ ]:
games_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1512 entries, 0 to 1511
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         1512 non-null   int64
 1   Title              1512 non-null   object
 2   Release Date       1512 non-null   object
 3   Team               1511 non-null   object
 4   Rating             1499 non-null   float64
 5   Times Listed       1512 non-null   object
 6   Number of Reviews  1512 non-null   object
 7   Genres             1512 non-null   object
 8   Summary            1511 non-null   object
 9   Reviews            1512 non-null   object
 10  Plays              1512 non-null   object
 11  Playing            1512 non-null   object
 12  Backlogs           1512 non-null   object
 13  Wishlist           1512 non-null   object
 14  Adventure          1512 non-null   int64
 15  RPG                1512 non-null   int64
 16  Platform           1512 non-null   int64
 17  Shooter            1512 non-null   int64
 18  Indie              1512 non-null   int64
dtypes: float64(1), int64(6), object(12)
memory usage: 224.6+ KB

In [ ]:
games_data.dropna(subset=['Rating'],inplace=True)

In [ ]:
games_data[['Title','Rating','Times Listed','Number of Reviews','Plays','Playing','Backlogs','Wishlist']].duplicated().value_counts()

False    1105
Name: count, dtype: int64

In [ ]:
games_data.drop_duplicates(subset=['Title','Rating','Times Listed','Number of Reviews','Plays','Playing','Backlogs','Wishlist'],inplace=True)

In [ ]:
games_data

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist,Adventure,RPG,Platform,Shooter,Indie
0,0,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3900.0,3900.0,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",17000.0,3800.0,4600.0,4800.0,1,1,0,0,0
1,1,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2900.0,2900.0,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,21000.0,3200.0,6300.0,3600.0,1,1,0,0,1
2,2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","['Nintendo', 'Nintendo EPD Production Group No...",4.4,4300.0,4300.0,"['Adventure', 'RPG']",The Legend of Zelda: Breath of the Wild is the...,['This game is the game (that is not CS:GO) th...,30000.0,2500.0,5000.0,2600.0,1,1,0,0,0
3,3,Undertale,"Sep 15, 2015","['tobyfox', '8-4']",4.2,3500.0,3500.0,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...","A small child falls into the Underground, wher...",['soundtrack is tied for #1 with nier automata...,28000.0,679,4900.0,1800.0,1,1,0,0,1
4,4,Hollow Knight,"Feb 24, 2017",['Team Cherry'],4.4,3000.0,3000.0,"['Adventure', 'Indie', 'Platform']",A 2D metroidvania with an emphasis on close co...,"[""this games worldbuilding is incredible, with...",21000.0,2400.0,8300.0,2300.0,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1507,1507,Back to the Future: The Game,"Dec 22, 2010",['Telltale Games'],3.2,94,94,"['Adventure', 'Point-and-Click']",Back to the Future: The Game is one of Telltal...,['Very enjoyable game. The story adds onto the...,763,5,223,67,1,0,0,0,0
1508,1508,Team Sonic Racing,"May 21, 2019","['Sumo Digital', 'Sega']",2.9,264,264,"['Arcade', 'Racing']",Team Sonic Racing combines the best elements o...,"['jogo morto mas bom', 'not my cup of tea', ""C...",1500.0,49,413,107,0,0,0,0,0
1509,1509,Dragon's Dogma,"May 22, 2012",['Capcom'],3.7,210,210,"['Brawler', 'RPG']","Set in a huge open world, Dragon’s Dogma: Dark...","['Underrated.', 'A grandes rasgos, es como un ...",1100.0,45,487,206,0,1,0,0,0
1510,1510,Baldur's Gate 3,"Oct 06, 2020",['Larian Studios'],4.1,165,165,"['Adventure', 'RPG', 'Strategy', 'Tactical', '...","An ancient evil has returned to Baldur's Gate,...",['Bu türe bu oyunla girmeye çalışmak hataydı s...,269,79,388,602,1,1,0,0,0
1511,1511,The LEGO Movie Videogame,"Feb 04, 2014","['WB Games', 'TT Fusion']",2.8,184,184,"['Adventure', 'Puzzle']",Join Emmet and an unlikely group of resistance...,"['Legal', 'Pretty Average Lego Game But It Was...",1700.0,11,239,73,1,0,0,0,0

In [ ]:
games_data.drop(games_data[games_data['Release Date'] == 'releases on TBD'].index, inplace=True)

In [ ]:
games_data['Release Date'].isnull().value_counts()

Release Date
False    1105
Name: count, dtype: int64

#vgsales

In [ ]:
import pandas as pd
vgsales_data=pd.read_csv("vgsales.csv")

#vgsales data cleaning by removing duplicate row from name, genre,sales

In [ ]:
vg_first_list=vgsales_data[['Name','Genre']]
vg_first_list

                                                   Name         Genre
0                                            Wii Sports        Sports
1                                     Super Mario Bros.      Platform
2                                        Mario Kart Wii        Racing
3                                     Wii Sports Resort        Sports
4                              Pokemon Red/Pokemon Blue  Role-Playing
...                                                 ...           ...
16593                Woody Woodpecker in Crazy Castle 5      Platform
16594                     Men in Black II: Alien Escape       Shooter
16595  SCORE International Baja 1000: The Official Game        Racing
16596                                        Know How 2        Puzzle
16597                                  Spirits & Spells      Platform

[16598 rows x 2 columns]

In [ ]:
vg_sec_list=vgsales_data.iloc[:,-5:]
vg_sec_list

       NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
0         41.49     29.02      3.77         8.46         82.74
1         29.08      3.58      6.81         0.77         40.24
2         15.85     12.88      3.79         3.31         35.82
3         15.75     11.01      3.28         2.96         33.00
4         11.27      8.89     10.22         1.00         31.37
...         ...       ...       ...          ...           ...
16593      0.01      0.00      0.00         0.00          0.01
16594      0.01      0.00      0.00         0.00          0.01
16595      0.00      0.00      0.00         0.00          0.01
16596      0.00      0.01      0.00         0.00          0.01
16597      0.01      0.00      0.00         0.00          0.01

[16598 rows x 5 columns]

In [ ]:
vg_final_list=pd.concat([vg_first_list,vg_sec_list],axis=1)
(vg_final_list)

,Name,Genre,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Wii Sports,Sports,41.49,29.02,3.77,8.46,82.74
1,Super Mario Bros.,Platform,29.08,3.58,6.81,0.77,40.24
2,Mario Kart Wii,Racing,15.85,12.88,3.79,3.31,35.82
3,Wii Sports Resort,Sports,15.75,11.01,3.28,2.96,33.00
4,Pokemon Red/Pokemon Blue,Role-Playing,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...
16593,Woody Woodpecker in Crazy Castle 5,Platform,0.01,0.00,0.00,0.00,0.01
16594,Men in Black II: Alien Escape,Shooter,0.01,0.00,0.00,0.00,0.01
16595,SCORE International Baja 1000: The Official Game,Racing,0.00,0.00,0.00,0.00,0.01
16596,Know How 2,Puzzle,0.00,0.01,0.00,0.00,0.01
16597,Spirits & Spells,Platform,0.01,0.00,0.00,0.00,0.01

In [ ]:
vgsales_data.drop_duplicates(vg_final_list,inplace=True)

In [ ]:
vgsales_data

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

#Normalize genre, platform, and publisher names.

In [ ]:
vgsales_data[['Genre','Platform','Publisher']].isnull().value_counts()

Genre  Platform  Publisher
False  False     False        16471
                 True            58
Name: count, dtype: int64

In [ ]:
vgsales_data['Publisher'].value_counts()
#Electronic Arts

Publisher
Electronic Arts                 1351
Activision                       971
Namco Bandai Games               928
Ubisoft                          919
Konami Digital Entertainment     829
                                ...
Media Entertainment                1
New World Computing                1
Genterprise                        1
Rain Games                         1
UIG Entertainment                  1
Name: count, Length: 578, dtype: int64

In [ ]:
vgsales_data['Publisher'].fillna('Electronic Arts',inplace=True)

/tmp/ipykernel_2027/2447566573.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  vgsales_data['Publisher'].fillna('Electronic Arts',inplace=True)

In [ ]:
vgsales_data['Publisher'].value_counts()

Publisher
Electronic Arts                 1409
Activision                       971
Namco Bandai Games               928
Ubisoft                          919
Konami Digital Entertainment     829
                                ...
Media Entertainment                1
New World Computing                1
Genterprise                        1
Rain Games                         1
UIG Entertainment                  1
Name: count, Length: 578, dtype: int64

In [ ]:
vgsales_data[['Genre','Platform','Publisher']].isnull().value_counts()

Genre  Platform  Publisher
False  False     False        16529
Name: count, dtype: int64

In [ ]:
vgsales_data[['Genre','Platform','Publisher']]

              Genre Platform   Publisher
0            Sports      Wii    Nintendo
1          Platform      NES    Nintendo
2            Racing      Wii    Nintendo
3            Sports      Wii    Nintendo
4      Role-Playing       GB    Nintendo
...             ...      ...         ...
16593      Platform      GBA       Kemco
16594       Shooter       GC  Infogrames
16595        Racing      PS2  Activision
16596        Puzzle       DS    7G//AMES
16597      Platform      GBA     Wanadoo

[16529 rows x 3 columns]

In [ ]:
import pandas as pd

# Save DataFrame to CSV
#vgsales_data.to_csv("vgsales_data.csv", index=False)
games_data.to_csv("games_data.csv", index=False)